// Technology registry: maps the names used in content/site.mjs to a visual.
//   logo  -> self-hosted brand mark in assets/img/tech/<logo>.svg (see scripts/fetch-logos.mjs)
//   icon  -> concept icon drawn inline (scripts/components.mjs ICONS)
// Names that are not listed render as plain text chips.

const DEVICON = (path) => `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${path}.svg`;
const SIMPLE = (slug) => `https://cdn.jsdelivr.net/npm/simple-icons@13/icons/${slug}.svg`;

// Logo sources. `fill` recolors single-color marks that would disappear on a dark background.
export const LOGOS = {
  python: { src: DEVICON('python/python-original') },
  java: { src: DEVICON('java/java-original') },
  typescript: { src: DEVICON('typescript/typescript-original') },
  javascript: { src: DEVICON('javascript/javascript-original') },
  fastapi: { src: DEVICON('fastapi/fastapi-original') },
  spring: { src: DEVICON('spring/spring-original') },
  nodejs: { src: DEVICON('nodejs/nodejs-original') },
  flask: { src: SIMPLE('flask'), fill: '#e8edf5' },
  django: { src: SIMPLE('django'), fill: '#44b78b' },
  graphql: { src: DEVICON('graphql/graphql-plain') },
  swagger: { src: DEVICON('swagger/swagger-original') },
  react: { src: DEVICON('react/react-original') },
  nextjs: { src: SIMPLE('nextdotjs'), fill: '#e8edf5' },
  redux: { src: DEVICON('redux/redux-original') },
  tailwind: { src: DEVICON('tailwindcss/tailwindcss-original') },
  openai: { src: SIMPLE('openai'), fill: '#e8edf5' },
  anthropic: { src: SIMPLE('anthropic'), fill: '#e3b48c' },
  langchain: { src: SIMPLE('langchain'), fill: '#7fd3bd' },
  huggingface: { src: SIMPLE('huggingface'), fill: '#ffd21e' },
  pytorch: { src: DEVICON('pytorch/pytorch-original') },
  tensorflow: { src: DEVICON('tensorflow/tensorflow-original') },
  sklearn: { src: DEVICON('scikitlearn/scikitlearn-original') },
  opencv: { src: DEVICON('opencv/opencv-original') },
  postgresql: { src: DEVICON('postgresql/postgresql-original') },
  mysql: { src: SIMPLE('mysql'), fill: '#5fa8d8' },
  mssql: { src: DEVICON('microsoftsqlserver/microsoftsqlserver-plain') },
  mongodb: { src: DEVICON('mongodb/mongodb-original') },
  dynamodb: { src: DEVICON('dynamodb/dynamodb-original') },
  redis: { src: DEVICON('redis/redis-original') },
  elasticsearch: { src: DEVICON('elasticsearch/elasticsearch-original') },
  spark: { src: DEVICON('apachespark/apachespark-original') },
  aws: { src: SIMPLE('amazonwebservices'), fill: '#ff9900' },
  gcp: { src: DEVICON('googlecloud/googlecloud-original') },
  docker: { src: DEVICON('docker/docker-original') },
  kubernetes: { src: DEVICON('kubernetes/kubernetes-plain') },
  terraform: { src: DEVICON('terraform/terraform-original') },
  githubactions: { src: DEVICON('githubactions/githubactions-original') },
  jenkins: { src: DEVICON('jenkins/jenkins-original') },
  gitlab: { src: DEVICON('gitlab/gitlab-original') },
  nginx: { src: DEVICON('nginx/nginx-original') },
  kafka: { src: SIMPLE('apachekafka'), fill: '#e8edf5' },
  rabbitmq: { src: DEVICON('rabbitmq/rabbitmq-original') },
  android: { src: DEVICON('android/android-original') },
  flutter: { src: DEVICON('flutter/flutter-original') },
  dart: { src: DEVICON('dart/dart-original') },
  firebase: { src: DEVICON('firebase/firebase-original') },
  prometheus: { src: DEVICON('prometheus/prometheus-original') },
  celery: { src: SIMPLE('celery'), fill: '#a9cc54' },
  playwright: { src: DEVICON('playwright/playwright-original') },
  gemini: { src: SIMPLE('googlegemini'), fill: '#8e9cff' },
};

// Display name (or alias) -> visual.
const MAP = {
  Python: { logo: 'python' },
  'Python SDK': { logo: 'python' },
  Java: { logo: 'java' },
  TypeScript: { logo: 'typescript' },
  JavaScript: { logo: 'javascript' },
  SQL: { icon: 'database' },
  FastAPI: { logo: 'fastapi' },
  'Spring Boot': { logo: 'spring' },
  'Node.js': { logo: 'nodejs' },
  Flask: { logo: 'flask' },
  Django: { logo: 'django' },
  REST: { icon: 'arrows' },
  GraphQL: { logo: 'graphql' },
  'GraphQL API': { logo: 'graphql' },
  gRPC: { icon: 'zap' },
  'OpenAPI / Swagger': { logo: 'swagger' },
  React: { logo: 'react' },
  'Next.js': { logo: 'nextjs' },
  Redux: { logo: 'redux' },
  'Tailwind CSS': { logo: 'tailwind' },
  'OpenAI API': { logo: 'openai' },
  'Anthropic Claude': { logo: 'anthropic' },
  LangChain: { logo: 'langchain' },
  RAG: { icon: 'sparkles' },
  'Vector search': { icon: 'scan' },
  'Vector Search': { icon: 'scan' },
  'Hugging Face Transformers': { logo: 'huggingface' },
  PyTorch: { logo: 'pytorch' },
  TensorFlow: { logo: 'tensorflow' },
  'scikit-learn': { logo: 'sklearn' },
  OpenCV: { logo: 'opencv' },
  YOLOv3: { icon: 'eye' },
  PostgreSQL: { logo: 'postgresql' },
  'PostgreSQL + pgvector': { logo: 'postgresql' },
  pgvector: { logo: 'postgresql' },
  MySQL: { logo: 'mysql' },
  MSSQL: { logo: 'mssql' },
  MongoDB: { logo: 'mongodb' },
  DynamoDB: { logo: 'dynamodb' },
  Redis: { logo: 'redis' },
  Elasticsearch: { logo: 'elasticsearch' },
  'Apache Spark': { logo: 'spark' },
  'Spark Streaming': { logo: 'spark' },
  MLlib: { logo: 'spark' },
  AWS: { logo: 'aws' },
  'AWS Lambda': { logo: 'aws' },
  Lambda: { logo: 'aws' },
  'Step Functions': { logo: 'aws' },
  S3: { logo: 'aws' },
  'AWS SageMaker': { logo: 'aws' },
  CloudWatch: { logo: 'aws' },
  'Google Cloud': { logo: 'gcp' },
  Docker: { logo: 'docker' },
  Kubernetes: { logo: 'kubernetes' },
  Terraform: { logo: 'terraform' },
  'GitHub Actions': { logo: 'githubactions' },
  Jenkins: { logo: 'jenkins' },
  'GitLab CI/CD': { logo: 'gitlab' },
  Nginx: { logo: 'nginx' },
  Kafka: { logo: 'kafka' },
  'Apache Kafka': { logo: 'kafka' },
  RabbitMQ: { logo: 'rabbitmq' },
  Microservices: { icon: 'blocks' },
  'Event-driven architecture': { icon: 'workflow' },
  'Event-Driven Architecture': { icon: 'workflow' },
  FHIR: { icon: 'heart' },
  Ganache: { icon: 'link' },
  Blockchain: { icon: 'link' },
  Android: { logo: 'android' },
  Flutter: { logo: 'flutter' },
  Dart: { logo: 'dart' },
  Firebase: { logo: 'firebase' },
  Prometheus: { logo: 'prometheus' },
  Celery: { logo: 'celery' },
  Playwright: { logo: 'playwright' },
  'Google Gemini': { logo: 'gemini' },
  WebSockets: { icon: 'radio' },
  FAISS: { icon: 'scan' },
  HNSW: { icon: 'network' },
  BM25: { icon: 'scan' },
  RocksDB: { icon: 'database' },
  BullMQ: { icon: 'workflow' },
  'Multi-agent AI': { icon: 'sparkles' },
  'Write-ahead log': { icon: 'layers' },
};

export const techVisual = (name) => MAP[name] || null;
